function [tree] = sci_match(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab match()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(0,0)
tree.lhs(1).type=Type(Double,Real)
endfunction
