function str = randomName
% choose a random name
nm = {'Aaron', 'Abhinav', 'Akshay', 'Alan', 'Albert', ...
'Alec', 'Alessandro', 'Alex', 'Alexander', 'Alicia', ...
'Alison', 'Allen', 'Alline', 'Allison', 'Allyana', ...
'Amy', 'Anders', 'Andre', 'Andrea', 'Andreas', ...
'Andrew', 'Andrzej', 'Andy', 'Angela', 'Ani', ...
'Ankit', 'Ann', 'Annabelle', 'Anne', 'Antoine', ...
'Archie', 'Arjun', 'Armando', 'Arthur', 'Arwa  ', ...
'Ashley', 'Ashok', 'Ashwin', 'Austin', 'Away', ...
'Bachu', 'Barbara', 'Barry', 'Becky', 'Bengt', ...
'Bennett', 'Bent', 'Bernard', 'Beth', 'Betsy', ...
'Bill', 'Blaine', 'Blair', 'Bob', 'Bobby', ...
'Bradford', 'Bradley', 'Brandon', 'Brenda', 'Brett ', ...
'Brian', 'Brock', 'Brooke', 'Bruce', 'Bruno', ...
'Bryan', 'Butch', 'Carl', 'Carla', 'Carol', ...
'Carole', 'Caroline', 'Carolyn', 'Carri', 'Catherine', ...
'Cathryn', 'Cathy', 'Charles', 'Charlotte', 'Chelcea', ...
'Cheryl', 'Chirag', 'Chris', 'Chrissy', 'Christian', ...
'Christina', 'Cindy', 'Claude', 'Clayton', 'Cliff', ...
'Clifford', 'Clyde ', 'Cody ', 'Colin', 'Constantinos', ...
'Cooper ', 'Cory', 'Craig', 'Cynthia', 'Dale', 'Damon', ...
'Dan', 'Dana', 'Daniel', 'Daniyal ', 'Darby', 'Dave', ...
'David', 'Dawn', 'Deanna', 'Deborah', 'Debra', 'Denise', ...
'Dennis', 'Denny', 'Derek', 'Diane', 'Dick', 'Dimitri', ...
'Dipen', 'Don', 'Donald', 'Donna', 'Doris ', 'Dorothy', ...
'Doug', 'Douglas', 'Drew', 'Duane', 'Dwain', 'Dwight', ...
'Ed', 'Eddie ', 'Edison', 'Edward', 'Elke', 'Ellen', ...
'Emma', 'Enzo', 'Eric', 'Ernie', 'Ernst', 'Eva', ...
'Faith', 'Floyd', 'Frank', 'Francois', 'Fred', 'Frederick', ...
'Garry', 'Gary', 'Gaurav ', 'Gene', 'Geoff', 'Geoffrey', ...
'George', 'Gerald', 'Gerhard', 'Giampiero', 'Gil', 'Gilles', ...
'Glen', 'Gloria', 'Goran', 'Gordon', 'Graeme', 'Graham', ...
'Grant', 'Greg', 'Gregg', 'Gregory', 'Gunnar', 'Guy ', ...
'Gwen', 'Haagen', 'Harlan', 'Harland', 'Harold', 'Harriett', ...
'Harry', 'Heather', 'Henri', 'Henrik', 'Henry', 'Herve', ...
'Hilda', 'Hillary', 'Howard', 'Huaxing', 'Hugh', 'Hut', ...
'Ian', 'Irfan', 'Jack', 'Jackie', 'Jacky', 'Jacqueline', ...
'Jalisa', 'James', 'Jan', 'Jana', 'Janet', 'Jan-Ola', ...
'Jarek', 'Jason', 'Jean-Christophe', 'Jean-Claude', 'Jeanette', ...
'Jean-Marie', 'Jeannine', 'Jean-Pierre', 'Jeff', 'Jenn', ...
'Jennifer', 'Jeremiah', 'Jerry', 'Jessica ', 'Jill', 'Jim', ...
'Jo', 'Joan', 'Jocelyn', 'Johan', 'John', 'Joi', 'Jon', ...
'Jonathan', 'Jorge', 'Jose', 'Joseph', 'Josh', 'Jovo', ...
'Juan', 'Judson', 'Juergen', 'Julie', 'Kalyan', 'Karen', ...
'Karl', 'Karsten', 'Kathy', 'Katie', 'Katy', 'Kelley', 'Kelly', ...
'Ken', 'Kenneth', 'Keven', 'Kevin', 'Kim', 'Kimberley', ...
'Kimberly ', 'Kishore', 'Klaus', 'Konstantinos', 'Kris', ...
'Kristin', 'Kurt', 'Kyle', 'Laird', 'Lamar', 'Lance', ...
'Larry', 'Lars', 'Latoria', 'Laura', 'Laurent', 'Laurie', ...
'Ledlie', 'Lee', 'Leif', 'Leisha', 'Leo', 'Leonard', ...
'LerVerne', 'Lesley ', 'Leslie', 'Levien', 'Linda', 'Lindsey', ...
'Ling', 'Lionnel', 'Lisa', 'Lloyd', 'Lottie', 'Lou', ...
'Louis', 'Louise ', 'Lucas', 'Lyn', 'Lynn', 'Lynne', ...
'Mahmut', 'Malcolm', 'Mallory ', 'Mani', 'Maretta', 'Maria', ...
'Marianne', 'Marie-Helene', 'Mario', 'Marita', 'Mark', ...
'Marsha', 'Martin', 'Mary', 'Masha', 'Matt', 'Maureen', ...
'Maurice', 'Maxim', 'Melissa', 'Michael', 'Michele', ...
'Mike', 'Milena', 'Mitch', 'Molly', 'Mona', 'Monica', ...
'Morton', 'Mostafa', 'Mustaque', 'Nabil', 'Nancy', ...
'Nathan', 'Neha', 'Neil', 'Nelson', 'Neville', 'Nicholas', ...
'Niels', 'Nigel', 'Norberto', 'Norman', 'Ofer', 'Olin', ...
'Olivia', 'Orest', 'Otto', 'Paige', 'Palmer', 'Pam', ...
'Pamela', 'Pascal', 'Pat', 'Patrick', 'Paul', 'Pauline', ...
'Peggy', 'Pete', 'Peter', 'Phil', 'Philip','Philippe', ...
'Phillip', 'Piero', 'Pierre', 'Pranas', 'Prerna  ', 'Priya', ...
'Raghav', 'Raj', 'Raja', 'Ramesh', 'Randall', 'Randolph', ...
'Randy', 'Rashmi', 'Ray', 'Raymond', 'Renalto', 'Rich', ...
'Richard', 'Rick', 'Rob', 'Robert', 'Roger', 'Roland', ...
'Rolf', 'Ron', 'Ronald', 'Ross', 'Rubin', 'Rudi', ...
'Rudolph', 'Russ', 'Rusty', 'Ryan', 'Sam', 'Samuel', ...
'Santosh', 'Sara ', 'Sarah', 'Saun', 'Scott', 'Sean ', ...
'Serena', 'Sham', 'Shanita', 'Shannon', 'Shardul', 'Sharon', ...
'Sheri', 'Sherry', 'Silvino', 'Simon', 'Spencer', 'Stan', ...
'Stanley', 'Stephanie', 'Stephen', 'Steve', 'Susan ', ...
'Suzanne', 'Sven', 'Talib', 'Tammy ', 'Tanya', 'Tara', ...
'Tauhira', 'Ted', 'Tempo', 'Teresa', 'Terry', 'Thad', ...
'Thea', 'Thies', 'Thom', 'Thomas', 'Tim', 'Tina', ...
'Todd', 'Tom', 'Tommy', 'Tongyu', 'Tony', 'Tonya', ...
'Torbjorn', 'Tracy', 'Trask', 'Trish', 'Tucker', ...
'Uwanna', 'Val', 'Valerie', 'Varun', 'Vasily', ...
'Vibeke', 'Vicky', 'Victor', 'Vig', 'Vijay', 'Violeta', ...
'Virgina', 'Walt', 'Walter', 'Wanda', 'Ward', 'Wayne', ...
'Wenchang', 'Wendy', 'Wenke', 'William', 'Willy', 'Wing', ...
'Wolfgang', 'Wynn', 'Xavier', 'Yan', 'Yannis', ...
'YingQing', 'Ylonda', 'Zach', 'Zeke', 'Zia' };

n = length(nm);
index = randint(1, 1, [1, n]);
str = nm{index};

