% 7.3	We need to be able to transform numerical vectors into cell arrays,
% and cell arrays to vectors.
% a.	Write a function called vecToCells that converts a vector of numbers into a cell array of strings. 
%       Each item in the string will be the value of the cell array as generated by sprintf(…) using the 
%       format string '%g'.
% b.	To test this function, build a vector with random length (between 20 and 100) of random numbers in
%       the range (0 ... 1,000,000), and pass this vector to your vecToCells function, displaying the results
%       in the Command window.
% c.	Write and test a function that accepts a cell array of strings and builds a vector of numbers of the 
%       same length. Each item in the output vector will be the length of the strings in each cell array.
clear
clc

%% Part b
vec = (rand(1, round((rand*80)+20)) * 1000000);
disp('Output of vecToCells function')
disp(vecToCells(vec))

%%
%% Part c
%% Test Case: 
disp('Output of cellToVec function')
disp(cellToVec({'', '1', '1234567890', 'a', 'abcd'}))
%% Should return : 
%% ans =
%% [0, 1, 10, ,1, 4]

% cellToVec({5, 'abc'})

%% Should return :
%% ??? Element 1 in the cell array is not a character array

% cellToVec(5)

%% Should return :
%% ??? Input is not a cell array


